package com.mycompany.juegopeleasgui.fe;

import com.mycompany.juegopeleasgui.be.Archivo;
import com.mycompany.juegopeleasgui.be.Casilla;
import com.mycompany.juegopeleasgui.be.tablero.Tablero;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Toolkit;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

public class AbrirTablero extends javax.swing.JFrame {

    public AbrirTablero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCargarTablero = new javax.swing.JButton();
        pnlPrevisualizador = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCargarTablero.setText("Cargar Tablero");
        btnCargarTablero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarTableroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrevisualizadorLayout = new javax.swing.GroupLayout(pnlPrevisualizador);
        pnlPrevisualizador.setLayout(pnlPrevisualizadorLayout);
        pnlPrevisualizadorLayout.setHorizontalGroup(
            pnlPrevisualizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );
        pnlPrevisualizadorLayout.setVerticalGroup(
            pnlPrevisualizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 253, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(btnCargarTablero)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(pnlPrevisualizador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrevisualizador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCargarTablero)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarTableroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarTableroActionPerformed
        JFileChooser archivoSeleccionado = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.TH", ".th");

        //archivoSeleccionado.setFileFilter(filtro);
        archivoSeleccionado.showOpenDialog(null);
        Archivo archivo = new Archivo();
        archivo.leerArchivo(archivoSeleccionado.getSelectedFile().getAbsolutePath());
        Tablero tablero = new Tablero("", 8, 8);
        mostrarTablero((Casilla[][]) tablero.crearTablero());
    }//GEN-LAST:event_btnCargarTableroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarTablero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlPrevisualizador;
    // End of variables declaration//GEN-END:variables
    public void mostrarMapas(JComponent texto) {
       // FramePrincipal principal = new FramePrincipal();
        //panelPrevisualizador.setLocation((principal.getWidth() / 2) - 400, (principal.getHeight() / 2) - 250);

        pnlPrevisualizador.remove(texto);
        pnlPrevisualizador.setLayout(new FlowLayout());
        //panelPrevisualizador.setSize(new Dimension(900, 500));
        pnlPrevisualizador.setBackground(Color.LIGHT_GRAY);
        pnlPrevisualizador.add(texto);
    }

    public void mostrarTablero(Casilla[][] mapa) {
        int tamaño = ((int) (Toolkit.getDefaultToolkit().getScreenSize().getHeight() / mapa.length)) * 2 / 3;
        int posicionX = 10;
        int posicionY = 10;
        int anchoCasilla;
        int largoCasilla = 0;

        for (int i = 0; i < mapa.length; i++) {
            anchoCasilla = pnlPrevisualizador.getWidth() / mapa.length - 5;
            for (int j = 0; j < mapa[i].length; j++) {

                largoCasilla = pnlPrevisualizador.getHeight() / mapa[i].length - 5;
                mapa[i][j] = new Casilla(tamaño);
                mapa[i][j].setBounds(posicionX, posicionY, anchoCasilla, largoCasilla);
                mostrarMapas(mapa[i][j]);
                posicionX += anchoCasilla + 5;
            }
            posicionX = 10;
            posicionY += largoCasilla + 5;
        }

    }
}
