package com.mycompany.juegopeleasgui.fe;

import com.mycompany.juegopeleasgui.be.jugadores.Usuario;

public class GenerarTablero extends javax.swing.JFrame {

    /**
     * Creates new form GenerarTablero
     */
    private Usuario usuario;

    public GenerarTablero(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGenerarTablero = new javax.swing.JPanel();
        lblGenerarTablero = new javax.swing.JLabel();
        btnCargarTablero = new javax.swing.JButton();
        btnCrearTablero = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlGenerarTablero.setBackground(new java.awt.Color(92, 239, 150));

        lblGenerarTablero.setBackground(new java.awt.Color(204, 255, 204));
        lblGenerarTablero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGenerarTablero.setForeground(new java.awt.Color(0, 0, 0));
        lblGenerarTablero.setText("Generar Tablero");

        btnCargarTablero.setBackground(new java.awt.Color(0, 153, 102));
        btnCargarTablero.setForeground(new java.awt.Color(0, 0, 0));
        btnCargarTablero.setText("Cargar Tablero");
        btnCargarTablero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarTableroActionPerformed(evt);
            }
        });

        btnCrearTablero.setBackground(new java.awt.Color(0, 153, 102));
        btnCrearTablero.setForeground(new java.awt.Color(0, 0, 0));
        btnCrearTablero.setText("Crear Tablero");

        btnRegresar.setBackground(new java.awt.Color(0, 255, 51));
        btnRegresar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegresar.setText("Regresar a Menu Principal");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGenerarTableroLayout = new javax.swing.GroupLayout(pnlGenerarTablero);
        pnlGenerarTablero.setLayout(pnlGenerarTableroLayout);
        pnlGenerarTableroLayout.setHorizontalGroup(
            pnlGenerarTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGenerarTableroLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnCargarTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCrearTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(pnlGenerarTableroLayout.createSequentialGroup()
                .addGroup(pnlGenerarTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGenerarTableroLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(lblGenerarTablero))
                    .addGroup(pnlGenerarTableroLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btnRegresar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlGenerarTableroLayout.setVerticalGroup(
            pnlGenerarTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGenerarTableroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGenerarTablero)
                .addGap(37, 37, 37)
                .addGroup(pnlGenerarTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearTablero)
                    .addComponent(btnCargarTablero))
                .addGap(48, 48, 48)
                .addComponent(btnRegresar)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGenerarTablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGenerarTablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnCargarTableroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarTableroActionPerformed
        AbrirTablero abrir = new AbrirTablero();
        abrir.setVisible(true);
    }//GEN-LAST:event_btnCargarTableroActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarTablero;
    private javax.swing.JButton btnCrearTablero;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel lblGenerarTablero;
    private javax.swing.JPanel pnlGenerarTablero;
    // End of variables declaration//GEN-END:variables
}
