package com.mycompany.juegopeleasgui.fe;

import com.mycompany.juegopeleasgui.Partida;
import com.mycompany.juegopeleasgui.be.articulos.Articulo;
import com.mycompany.juegopeleasgui.be.inventarios.ListaGenerica;
import com.mycompany.juegopeleasgui.be.jugadores.GuardarJugador;
import com.mycompany.juegopeleasgui.be.jugadores.IA;
import com.mycompany.juegopeleasgui.be.jugadores.Usuario;
import com.mycompany.juegopeleasgui.be.personajes.Jugable;

public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    private Usuario usuario;
    private IA ia;
    private ListaGenerica<Jugable> inventarioUsuario;
    private ListaGenerica<Articulo> inventarioArticulos;

    public MenuPrincipal(Usuario usuario, IA ia) {
        initComponents();
        this.usuario = usuario;
        this.ia = ia;
        inventarioUsuario = usuario.getInventarioUsuario();
        inventarioArticulos = usuario.getInventarioArticulos();
        lblCantidadOro.setText(usuario.getOro() + "");
        lblNombreTexto.setText(usuario.getNombre() + "");
        lblcantidadPuntuacion.setText(usuario.getPuntuacion() + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFrame = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblBienvenida = new javax.swing.JLabel();
        btnIniciarPartida = new javax.swing.JButton();
        btnTienda = new javax.swing.JButton();
        btnGeneracionTablero = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnRanking = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        lblOro = new javax.swing.JLabel();
        lblCantidadOro = new javax.swing.JLabel();
        lblNombreTexto = new javax.swing.JLabel();
        btnGuardarJugador = new javax.swing.JButton();
        lblPuntuacion = new javax.swing.JLabel();
        lblcantidadPuntuacion = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFrame.setBackground(new java.awt.Color(51, 102, 255));
        pnlFrame.setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("¡¡¡JUEGO PELEAS!!!");
        pnlFrame.add(lblTitulo);
        lblTitulo.setBounds(141, 37, 105, 16);

        lblBienvenida.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBienvenida.setForeground(new java.awt.Color(0, 0, 0));
        lblBienvenida.setText("BIENVENIDO");
        pnlFrame.add(lblBienvenida);
        lblBienvenida.setBounds(141, 6, 111, 25);

        btnIniciarPartida.setBackground(new java.awt.Color(255, 255, 255));
        btnIniciarPartida.setForeground(new java.awt.Color(0, 0, 0));
        btnIniciarPartida.setText("Iniciar Partida");
        btnIniciarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarPartidaActionPerformed(evt);
            }
        });
        pnlFrame.add(btnIniciarPartida);
        btnIniciarPartida.setBounds(123, 65, 150, 23);

        btnTienda.setBackground(new java.awt.Color(255, 255, 255));
        btnTienda.setForeground(new java.awt.Color(0, 0, 0));
        btnTienda.setText("Tienda");
        btnTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiendaActionPerformed(evt);
            }
        });
        pnlFrame.add(btnTienda);
        btnTienda.setBounds(123, 106, 150, 23);

        btnGeneracionTablero.setBackground(new java.awt.Color(255, 255, 255));
        btnGeneracionTablero.setForeground(new java.awt.Color(0, 0, 0));
        btnGeneracionTablero.setText("Generación Tablero");
        btnGeneracionTablero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneracionTableroActionPerformed(evt);
            }
        });
        pnlFrame.add(btnGeneracionTablero);
        btnGeneracionTablero.setBounds(123, 147, 150, 23);

        btnInventario.setBackground(new java.awt.Color(255, 255, 255));
        btnInventario.setForeground(new java.awt.Color(0, 0, 0));
        btnInventario.setText("Inventario");
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        pnlFrame.add(btnInventario);
        btnInventario.setBounds(123, 188, 150, 23);

        btnRanking.setBackground(new java.awt.Color(255, 255, 255));
        btnRanking.setForeground(new java.awt.Color(0, 0, 0));
        btnRanking.setText("Ranking");
        btnRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRankingActionPerformed(evt);
            }
        });
        pnlFrame.add(btnRanking);
        btnRanking.setBounds(123, 229, 150, 23);

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        pnlFrame.add(btnSalir);
        btnSalir.setBounds(123, 264, 150, 23);

        lblNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre.setText("Nombre del Jugador:");
        pnlFrame.add(lblNombre);
        lblNombre.setBounds(6, 311, 140, 16);

        lblOro.setForeground(new java.awt.Color(0, 0, 0));
        lblOro.setText("Oro del Jugador:");
        pnlFrame.add(lblOro);
        lblOro.setBounds(160, 310, 120, 16);

        lblCantidadOro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlFrame.add(lblCantidadOro);
        lblCantidadOro.setBounds(150, 340, 110, 20);

        lblNombreTexto.setBackground(new java.awt.Color(0, 0, 0));
        lblNombreTexto.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreTexto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlFrame.add(lblNombreTexto);
        lblNombreTexto.setBounds(10, 340, 111, 20);

        btnGuardarJugador.setText("Guardar Jugador");
        btnGuardarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarJugadorActionPerformed(evt);
            }
        });
        pnlFrame.add(btnGuardarJugador);
        btnGuardarJugador.setBounds(120, 390, 150, 23);

        lblPuntuacion.setForeground(new java.awt.Color(0, 0, 0));
        lblPuntuacion.setText("Puntuacion del Jugador");
        pnlFrame.add(lblPuntuacion);
        lblPuntuacion.setBounds(290, 310, 140, 16);

        lblcantidadPuntuacion.setForeground(new java.awt.Color(0, 0, 0));
        lblcantidadPuntuacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlFrame.add(lblcantidadPuntuacion);
        lblcantidadPuntuacion.setBounds(290, 340, 120, 20);

        jToggleButton1.setText("agregar punteo (prueba)");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        pnlFrame.add(jToggleButton1);
        jToggleButton1.setBounds(10, 420, 220, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFrame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        usuario.guardarPuntajes();
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiendaActionPerformed
        Tienda tienda = new Tienda(usuario, ia);
        tienda.setVisible(true);
        lblCantidadOro.setText(usuario.getOro() + "");
    }//GEN-LAST:event_btnTiendaActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        Inventario inventario = new Inventario(usuario);
        inventario.setVisible(true);
        lblCantidadOro.setText(usuario.getOro() + "");
        // inventarioUsuario.mostrarLista();
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRankingActionPerformed
        Ranking ranking = new Ranking(usuario);
        ranking.setVisible(true);
        usuario.guardarPuntajes();
        
        lblCantidadOro.setText(usuario.getOro() + "");
    }//GEN-LAST:event_btnRankingActionPerformed

    private void btnGeneracionTableroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneracionTableroActionPerformed
        GenerarTablero generarTablero = new GenerarTablero(usuario, ia);
        generarTablero.setVisible(true);
    }//GEN-LAST:event_btnGeneracionTableroActionPerformed

    private void btnIniciarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarPartidaActionPerformed
        Tienda tienda = new Tienda(usuario, ia);
        tienda.setVisible(true);
        lblCantidadOro.setText(usuario.getOro() + "");

    }//GEN-LAST:event_btnIniciarPartidaActionPerformed

    private void btnGuardarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarJugadorActionPerformed
        GuardarJugador guardarJugador = new GuardarJugador();
        guardarJugador.guardarArchivoBinario(usuario);
    }//GEN-LAST:event_btnGuardarJugadorActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        usuario.setPuntuacion(100);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGeneracionTablero;
    private javax.swing.JButton btnGuardarJugador;
    private javax.swing.JButton btnIniciarPartida;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnRanking;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTienda;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblCantidadOro;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreTexto;
    private javax.swing.JLabel lblOro;
    private javax.swing.JLabel lblPuntuacion;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblcantidadPuntuacion;
    private javax.swing.JPanel pnlFrame;
    // End of variables declaration//GEN-END:variables
}
