package com.mycompany.juegopeleasgui.fe;

import com.mycompany.juegopeleasgui.be.Archivo;

public class MostrarTableros extends javax.swing.JFrame {

    private Archivo miArchivo;

    public MostrarTableros() {
        initComponents();
        miArchivo = new Archivo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMostrarTableros = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnTableroMayorMenor = new javax.swing.JButton();
        btnTableroMenorMayor = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnTableroNormal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaTableros = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMostrarTableros.setLayout(null);

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnlMostrarTableros.add(jButton1);
        jButton1.setBounds(200, 470, 100, 23);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("TABLEROS");
        pnlMostrarTableros.add(jLabel1);
        jLabel1.setBounds(220, 10, 70, 30);

        btnTableroMayorMenor.setText("Mayor a menor");
        pnlMostrarTableros.add(btnTableroMayorMenor);
        btnTableroMayorMenor.setBounds(180, 400, 150, 23);

        btnTableroMenorMayor.setText("Menor a mayor");
        pnlMostrarTableros.add(btnTableroMenorMayor);
        btnTableroMenorMayor.setBounds(340, 400, 150, 23);

        jLabel2.setText("Como deseas ver los tableros");
        pnlMostrarTableros.add(jLabel2);
        jLabel2.setBounds(170, 370, 180, 16);

        btnTableroNormal.setText("Ver tableros normal");
        btnTableroNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTableroNormalActionPerformed(evt);
            }
        });
        pnlMostrarTableros.add(btnTableroNormal);
        btnTableroNormal.setBounds(10, 400, 160, 23);

        txtAreaTableros.setColumns(20);
        txtAreaTableros.setRows(5);
        jScrollPane1.setViewportView(txtAreaTableros);

        pnlMostrarTableros.add(jScrollPane1);
        jScrollPane1.setBounds(20, 50, 510, 310);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMostrarTableros, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMostrarTableros, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTableroNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTableroNormalActionPerformed
        String textoLeido;
        textoLeido = miArchivo.abrirArchivo();
        txtAreaTableros.setText(textoLeido);
    }//GEN-LAST:event_btnTableroNormalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTableroMayorMenor;
    private javax.swing.JButton btnTableroMenorMayor;
    private javax.swing.JButton btnTableroNormal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlMostrarTableros;
    private javax.swing.JTextArea txtAreaTableros;
    // End of variables declaration//GEN-END:variables
}
