package com.mycompany.juegopeleasgui.fe;

import com.mycompany.juegopeleasgui.be.Archivo;
import com.mycompany.juegopeleasgui.be.CrearTablero;
import com.mycompany.juegopeleasgui.be.jugadores.IA;
import com.mycompany.juegopeleasgui.be.jugadores.Usuario;
import com.mycompany.juegopeleasgui.be.tablero.Tablero;
import javax.swing.JOptionPane;

public class TableroDeJuego extends javax.swing.JFrame {

    /**
     * Creates new form TableroDeJuego
     */
    private CrearTablero crearTablero;
    private Tablero tableroNuevo;
    private Archivo archivo;
    private Usuario usuario;
    private IA ia;

    public TableroDeJuego(Usuario usuario, IA ia) {
        this.usuario = usuario;
        this.ia = ia; 
        initComponents();
        crearTablero = new CrearTablero(usuario, ia);
        archivo = new Archivo();
        btnCargarMapa.setVisible(false);
        JOptionPane.showMessageDialog(rootPane, "En esta ventana puedes pervisualizar los mapas disponibles y elegir la dificultad de la IA", "INSTRUCCIONES", HEIGHT);
        lblJugador.setVisible(true);
        txtPersonajePrincipal.setVisible(true);
        boxDificultad.setVisible(false);
        lblDificultad.setVisible(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTableroDeJuego = new javax.swing.JPanel();
        pnlTablero = new javax.swing.JPanel();
        lblTableroDeJuego = new javax.swing.JLabel();
        btnCargarMapa = new javax.swing.JButton();
        btnMostrarTableros = new javax.swing.JButton();
        boxDificultad = new javax.swing.JComboBox<>();
        lblDificultad = new javax.swing.JLabel();
        lblJugador = new javax.swing.JLabel();
        txtPersonajePrincipal = new javax.swing.JTextField();
        btnMostrarInventario = new javax.swing.JButton();
        btnRegresarPrincipal = new javax.swing.JButton();
        btnAtaqueArriba = new javax.swing.JButton();
        btnAtaqueDerecha = new javax.swing.JButton();
        btnAtaqueIzquierda = new javax.swing.JButton();
        btnAtaqueAbajo = new javax.swing.JButton();
        lblDireccionAtaque = new javax.swing.JLabel();
        lblDireccionMovimiento = new javax.swing.JLabel();
        btnMovimientoAbajo = new javax.swing.JButton();
        btnMovimientoIzquierda = new javax.swing.JButton();
        btnMovimientoArriba = new javax.swing.JButton();
        btnMovimientoDerecha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlTableroDeJuego.setBackground(new java.awt.Color(2, 178, 146));
        pnlTableroDeJuego.setPreferredSize(new java.awt.Dimension(1247, 1000));
        pnlTableroDeJuego.setLayout(null);

        pnlTablero.setBackground(new java.awt.Color(255, 204, 204));
        pnlTablero.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout pnlTableroLayout = new javax.swing.GroupLayout(pnlTablero);
        pnlTablero.setLayout(pnlTableroLayout);
        pnlTableroLayout.setHorizontalGroup(
            pnlTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 772, Short.MAX_VALUE)
        );
        pnlTableroLayout.setVerticalGroup(
            pnlTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );

        pnlTableroDeJuego.add(pnlTablero);
        pnlTablero.setBounds(10, 40, 774, 410);

        lblTableroDeJuego.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTableroDeJuego.setText("TABLERO DE JUEGO");
        pnlTableroDeJuego.add(lblTableroDeJuego);
        lblTableroDeJuego.setBounds(364, 7, 172, 25);

        btnCargarMapa.setText("Cargar Tablero");
        btnCargarMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarMapaActionPerformed(evt);
            }
        });
        pnlTableroDeJuego.add(btnCargarMapa);
        btnCargarMapa.setBounds(220, 470, 190, 23);

        btnMostrarTableros.setText("Mostrar Tableros");
        btnMostrarTableros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTablerosActionPerformed(evt);
            }
        });
        pnlTableroDeJuego.add(btnMostrarTableros);
        btnMostrarTableros.setBounds(20, 470, 190, 23);

        boxDificultad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        boxDificultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxDificultadActionPerformed(evt);
            }
        });
        pnlTableroDeJuego.add(boxDificultad);
        boxDificultad.setBounds(890, 80, 72, 22);

        lblDificultad.setForeground(new java.awt.Color(0, 0, 0));
        lblDificultad.setText("Elige una dificultad");
        pnlTableroDeJuego.add(lblDificultad);
        lblDificultad.setBounds(880, 60, 120, 16);

        lblJugador.setForeground(new java.awt.Color(0, 0, 0));
        lblJugador.setText("Selecciona  a tu jugador principal");
        pnlTableroDeJuego.add(lblJugador);
        lblJugador.setBounds(880, 10, 190, 16);

        txtPersonajePrincipal.setText("Escribe un numero de tu inventario");
        txtPersonajePrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPersonajePrincipalActionPerformed(evt);
            }
        });
        pnlTableroDeJuego.add(txtPersonajePrincipal);
        txtPersonajePrincipal.setBounds(870, 30, 200, 22);

        btnMostrarInventario.setText("Mostrar Inventario");
        btnMostrarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarInventarioActionPerformed(evt);
            }
        });
        pnlTableroDeJuego.add(btnMostrarInventario);
        btnMostrarInventario.setBounds(1100, 30, 140, 23);

        btnRegresarPrincipal.setText("Regresar a Menu Principal");
        btnRegresarPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarPrincipalActionPerformed(evt);
            }
        });
        pnlTableroDeJuego.add(btnRegresarPrincipal);
        btnRegresarPrincipal.setBounds(20, 510, 190, 23);

        btnAtaqueArriba.setText("N");
        btnAtaqueArriba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtaqueArribaActionPerformed(evt);
            }
        });
        pnlTableroDeJuego.add(btnAtaqueArriba);
        btnAtaqueArriba.setBounds(960, 310, 50, 30);

        btnAtaqueDerecha.setText("E");
        btnAtaqueDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtaqueDerechaActionPerformed(evt);
            }
        });
        pnlTableroDeJuego.add(btnAtaqueDerecha);
        btnAtaqueDerecha.setBounds(1020, 330, 50, 30);

        btnAtaqueIzquierda.setText("O");
        btnAtaqueIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtaqueIzquierdaActionPerformed(evt);
            }
        });
        pnlTableroDeJuego.add(btnAtaqueIzquierda);
        btnAtaqueIzquierda.setBounds(900, 330, 50, 30);

        btnAtaqueAbajo.setText("S");
        btnAtaqueAbajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtaqueAbajoActionPerformed(evt);
            }
        });
        pnlTableroDeJuego.add(btnAtaqueAbajo);
        btnAtaqueAbajo.setBounds(960, 350, 50, 30);

        lblDireccionAtaque.setForeground(new java.awt.Color(0, 0, 0));
        lblDireccionAtaque.setText("Selecciona una direccion de ataque");
        pnlTableroDeJuego.add(lblDireccionAtaque);
        lblDireccionAtaque.setBounds(880, 280, 210, 16);

        lblDireccionMovimiento.setForeground(new java.awt.Color(0, 0, 0));
        lblDireccionMovimiento.setText("Selecciona una direccion de movimiento");
        pnlTableroDeJuego.add(lblDireccionMovimiento);
        lblDireccionMovimiento.setBounds(880, 140, 230, 16);

        btnMovimientoAbajo.setText("S");
        pnlTableroDeJuego.add(btnMovimientoAbajo);
        btnMovimientoAbajo.setBounds(960, 210, 50, 30);

        btnMovimientoIzquierda.setText("O");
        pnlTableroDeJuego.add(btnMovimientoIzquierda);
        btnMovimientoIzquierda.setBounds(900, 190, 50, 30);

        btnMovimientoArriba.setText("N");
        pnlTableroDeJuego.add(btnMovimientoArriba);
        btnMovimientoArriba.setBounds(960, 170, 50, 30);

        btnMovimientoDerecha.setText("E");
        pnlTableroDeJuego.add(btnMovimientoDerecha);
        btnMovimientoDerecha.setBounds(1020, 190, 50, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlTableroDeJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 1253, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTableroDeJuego, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtaqueAbajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtaqueAbajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtaqueAbajoActionPerformed

    private void btnAtaqueIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtaqueIzquierdaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtaqueIzquierdaActionPerformed

    private void btnAtaqueDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtaqueDerechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtaqueDerechaActionPerformed

    private void btnAtaqueArribaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtaqueArribaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtaqueArribaActionPerformed

    private void btnRegresarPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarPrincipalActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarPrincipalActionPerformed

    private void btnMostrarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarInventarioActionPerformed
        Inventario inventario = new Inventario(usuario);
        inventario.setVisible(true);
    }//GEN-LAST:event_btnMostrarInventarioActionPerformed

    private void txtPersonajePrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPersonajePrincipalActionPerformed
        String principal = txtPersonajePrincipal.getText();
        int personajePrincipal = Integer.parseInt(principal) - 1;
        usuario.almacenarPrincipalUsuario(personajePrincipal);
        boxDificultad.setVisible(true);
        lblDificultad.setVisible(true);
    }//GEN-LAST:event_txtPersonajePrincipalActionPerformed

    private void boxDificultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxDificultadActionPerformed
        String dificultadString = boxDificultad.getSelectedItem().toString();
        int dificultad = Integer.parseInt(dificultadString);
        ia.setDificultad(dificultad);
        btnCargarMapa.setVisible(true);
    }//GEN-LAST:event_boxDificultadActionPerformed

    private void btnMostrarTablerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTablerosActionPerformed
        String textoLeido;
        textoLeido = archivo.abrirArchivo();
        System.out.println(textoLeido);
        JOptionPane.showMessageDialog(rootPane, textoLeido, "TABLEROS", 1);
    }//GEN-LAST:event_btnMostrarTablerosActionPerformed

    private void btnCargarMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarMapaActionPerformed
        crearTablero.leerArchivo();
        tableroNuevo = crearTablero.getNuevoTablero();
        tableroNuevo.anadirBotones(pnlTablero, this);
        btnCargarMapa.setVisible(false);
        btnMostrarTableros.setVisible(false);
        boxDificultad.setVisible(false);
        lblDificultad.setVisible(false);
        lblJugador.setVisible(true);
        txtPersonajePrincipal.setVisible(true);
    }//GEN-LAST:event_btnCargarMapaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxDificultad;
    private javax.swing.JButton btnAtaqueAbajo;
    private javax.swing.JButton btnAtaqueArriba;
    private javax.swing.JButton btnAtaqueDerecha;
    private javax.swing.JButton btnAtaqueIzquierda;
    private javax.swing.JButton btnCargarMapa;
    private javax.swing.JButton btnMostrarInventario;
    private javax.swing.JButton btnMostrarTableros;
    private javax.swing.JButton btnMovimientoAbajo;
    private javax.swing.JButton btnMovimientoArriba;
    private javax.swing.JButton btnMovimientoDerecha;
    private javax.swing.JButton btnMovimientoIzquierda;
    private javax.swing.JButton btnRegresarPrincipal;
    private javax.swing.JLabel lblDificultad;
    private javax.swing.JLabel lblDireccionAtaque;
    private javax.swing.JLabel lblDireccionMovimiento;
    private javax.swing.JLabel lblJugador;
    private javax.swing.JLabel lblTableroDeJuego;
    private javax.swing.JPanel pnlTablero;
    private javax.swing.JPanel pnlTableroDeJuego;
    private javax.swing.JTextField txtPersonajePrincipal;
    // End of variables declaration//GEN-END:variables
}
