package com.mycompany.juegopeleasgui.fe;

import com.mycompany.juegopeleasgui.Partida;
import com.mycompany.juegopeleasgui.be.Archivo;
import com.mycompany.juegopeleasgui.be.CrearTablero;
import com.mycompany.juegopeleasgui.be.inventarios.ListaGenerica;
import com.mycompany.juegopeleasgui.be.jugadores.IA;
import com.mycompany.juegopeleasgui.be.jugadores.Usuario;
import com.mycompany.juegopeleasgui.be.tablero.Tablero;
import javax.swing.JOptionPane;

public class TableroDeJuego extends javax.swing.JFrame {

    /**
     * Creates new form TableroDeJuego
     */
    private CrearTablero crearTablero;
    private Tablero tableroNuevo;
    private Archivo archivo;
    private Usuario usuario;
    private IA ia;
    private Partida partida;

    public TableroDeJuego(Usuario usuario, IA ia) {
        this.usuario = usuario;
        this.ia = ia;
        initComponents();
        crearTablero = new CrearTablero(usuario, ia);
        archivo = new Archivo();
        btnCargarMapa.setVisible(false);
        JOptionPane.showMessageDialog(rootPane, "En esta ventana puedes pervisualizar los mapas disponibles y elegir la dificultad de la IA", "INSTRUCCIONES", HEIGHT);
        lblJugadorPrincipal.setVisible(true);
        fieldPersonajePrincipal.setVisible(true);
        boxDificultad.setVisible(false);
        lblDificultad.setVisible(false);

        usuario.desactivarBotonesAtaque(lblDireccionAtaque, btnAtaqueArriba, btnAtaqueAbajo, btnAtaqueDerecha, btnAtaqueIzquierda);
        usuario.desactivarBotonesMovimiento(lblDireccionMovimiento, btnMovimientoArriba, btnMovimientoAbajo, btnMovimientoDerecha, btnMovimientoIzquierda);

        lblAcciones.setVisible(false);
        btnAtacar.setVisible(false);
        btnMover.setVisible(false);
        btnUsarArticulo.setVisible(false);
        btnIniciarPartida.setVisible(false);

        btnTerminarTurno.setVisible(false);
        btnNuevoTurno.setVisible(false);

        fieldIDTablero.setVisible(false);
        lblIDTablero.setVisible(false);
        btnMostrarTableros.setVisible(false);
        fieldArticuloAUsar.setVisible(false);
        lblSeleccionarArticulo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTableroDeJuego = new javax.swing.JPanel();
        pnlTablero = new javax.swing.JPanel();
        lblTableroDeJuego = new javax.swing.JLabel();
        btnCargarMapa = new javax.swing.JButton();
        btnMostrarTableros = new javax.swing.JButton();
        boxDificultad = new javax.swing.JComboBox<>();
        lblDificultad = new javax.swing.JLabel();
        lblJugadorPrincipal = new javax.swing.JLabel();
        fieldPersonajePrincipal = new javax.swing.JTextField();
        btnMostrarInventario = new javax.swing.JButton();
        btnRegresarPrincipal = new javax.swing.JButton();
        btnAtaqueArriba = new javax.swing.JButton();
        btnAtaqueDerecha = new javax.swing.JButton();
        btnAtaqueIzquierda = new javax.swing.JButton();
        btnAtaqueAbajo = new javax.swing.JButton();
        lblDireccionAtaque = new javax.swing.JLabel();
        lblDireccionMovimiento = new javax.swing.JLabel();
        btnMovimientoAbajo = new javax.swing.JButton();
        btnMovimientoIzquierda = new javax.swing.JButton();
        btnMovimientoArriba = new javax.swing.JButton();
        btnMovimientoDerecha = new javax.swing.JButton();
        lblAcciones = new javax.swing.JLabel();
        btnMover = new javax.swing.JButton();
        btnAtacar = new javax.swing.JButton();
        btnIniciarPartida = new javax.swing.JButton();
        btnUsarArticulo = new javax.swing.JButton();
        btnTerminarTurno = new javax.swing.JButton();
        btnNuevoTurno = new javax.swing.JButton();
        fieldIDTablero = new javax.swing.JTextField();
        lblIDTablero = new javax.swing.JLabel();
        fieldArticuloAUsar = new javax.swing.JTextField();
        lblSeleccionarArticulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlTableroDeJuego.setBackground(new java.awt.Color(2, 178, 146));
        pnlTableroDeJuego.setPreferredSize(new java.awt.Dimension(1247, 1000));
        pnlTableroDeJuego.setLayout(null);

        pnlTablero.setBackground(new java.awt.Color(255, 255, 255));
        pnlTablero.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout pnlTableroLayout = new javax.swing.GroupLayout(pnlTablero);
        pnlTablero.setLayout(pnlTableroLayout);
        pnlTableroLayout.setHorizontalGroup(
            pnlTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 848, Short.MAX_VALUE)
        );
        pnlTableroLayout.setVerticalGroup(
            pnlTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );

        pnlTableroDeJuego.add(pnlTablero);
        pnlTablero.setBounds(10, 40, 850, 440);

        lblTableroDeJuego.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTableroDeJuego.setText("TABLERO DE JUEGO");
        pnlTableroDeJuego.add(lblTableroDeJuego);
        lblTableroDeJuego.setBounds(364, 7, 172, 25);

        btnCargarMapa.setText("Cargar Tablero");
        btnCargarMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarMapaActionPerformed(evt);
            }
        });
        pnlTableroDeJuego.add(btnCargarMapa);
        btnCargarMapa.setBounds(250, 490, 190, 23);

        btnMostrarTableros.setText("Mostrar Tableros");
        btnMostrarTableros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTablerosActionPerformed(evt);
            }
        });
        pnlTableroDeJuego.add(btnMostrarTableros);
        btnMostrarTableros.setBounds(20, 490, 190, 23);

        boxDificultad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        boxDificultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxDificultadActionPerformed(evt);
            }
        });
        pnlTableroDeJuego.add(boxDificultad);
        boxDificultad.setBounds(300, 560, 72, 22);

        lblDificultad.setForeground(new java.awt.Color(0, 0, 0));
        lblDificultad.setText("Elige una dificultad");
        pnlTableroDeJuego.add(lblDificultad);
        lblDificultad.setBounds(280, 540, 120, 16);

        lblJugadorPrincipal.setForeground(new java.awt.Color(0, 0, 0));
        lblJugadorPrincipal.setText("Selecciona  a tu jugador principal");
        pnlTableroDeJuego.add(lblJugadorPrincipal);
        lblJugadorPrincipal.setBounds(880, 10, 190, 16);

        fieldPersonajePrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPersonajePrincipalActionPerformed(evt);
            }
        });
        pnlTableroDeJuego.add(fieldPersonajePrincipal);
        fieldPersonajePrincipal.setBounds(930, 30, 64, 22);

        btnMostrarInventario.setText("Mostrar Inventario");
        btnMostrarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarInventarioActionPerformed(evt);
            }
        });
        pnlTableroDeJuego.add(btnMostrarInventario);
        btnMostrarInventario.setBounds(900, 70, 140, 23);

        btnRegresarPrincipal.setText("Regresar a Menu Principal");
        btnRegresarPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarPrincipalActionPerformed(evt);
            }
        });
        pnlTableroDeJuego.add(btnRegresarPrincipal);
        btnRegresarPrincipal.setBounds(10, 610, 190, 23);

        btnAtaqueArriba.setText("N");
        btnAtaqueArriba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtaqueArribaActionPerformed(evt);
            }
        });
        pnlTableroDeJuego.add(btnAtaqueArriba);
        btnAtaqueArriba.setBounds(960, 310, 50, 30);

        btnAtaqueDerecha.setText("E");
        btnAtaqueDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtaqueDerechaActionPerformed(evt);
            }
        });
        pnlTableroDeJuego.add(btnAtaqueDerecha);
        btnAtaqueDerecha.setBounds(1020, 330, 50, 30);

        btnAtaqueIzquierda.setText("O");
        btnAtaqueIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtaqueIzquierdaActionPerformed(evt);
            }
        });
        pnlTableroDeJuego.add(btnAtaqueIzquierda);
        btnAtaqueIzquierda.setBounds(900, 330, 50, 30);

        btnAtaqueAbajo.setText("S");
        btnAtaqueAbajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtaqueAbajoActionPerformed(evt);
            }
        });
        pnlTableroDeJuego.add(btnAtaqueAbajo);
        btnAtaqueAbajo.setBounds(960, 350, 50, 30);

        lblDireccionAtaque.setForeground(new java.awt.Color(0, 0, 0));
        lblDireccionAtaque.setText("Selecciona una direccion de ataque");
        pnlTableroDeJuego.add(lblDireccionAtaque);
        lblDireccionAtaque.setBounds(880, 280, 210, 16);

        lblDireccionMovimiento.setForeground(new java.awt.Color(0, 0, 0));
        lblDireccionMovimiento.setText("Selecciona una direccion de movimiento");
        pnlTableroDeJuego.add(lblDireccionMovimiento);
        lblDireccionMovimiento.setBounds(880, 140, 230, 16);

        btnMovimientoAbajo.setText("S");
        btnMovimientoAbajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovimientoAbajoActionPerformed(evt);
            }
        });
        pnlTableroDeJuego.add(btnMovimientoAbajo);
        btnMovimientoAbajo.setBounds(960, 210, 50, 30);

        btnMovimientoIzquierda.setText("O");
        btnMovimientoIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovimientoIzquierdaActionPerformed(evt);
            }
        });
        pnlTableroDeJuego.add(btnMovimientoIzquierda);
        btnMovimientoIzquierda.setBounds(900, 190, 50, 30);

        btnMovimientoArriba.setText("N");
        btnMovimientoArriba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovimientoArribaActionPerformed(evt);
            }
        });
        pnlTableroDeJuego.add(btnMovimientoArriba);
        btnMovimientoArriba.setBounds(960, 170, 50, 30);

        btnMovimientoDerecha.setText("E");
        btnMovimientoDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovimientoDerechaActionPerformed(evt);
            }
        });
        pnlTableroDeJuego.add(btnMovimientoDerecha);
        btnMovimientoDerecha.setBounds(1020, 190, 50, 30);

        lblAcciones.setForeground(new java.awt.Color(0, 0, 0));
        lblAcciones.setText("Elige una accion");
        pnlTableroDeJuego.add(lblAcciones);
        lblAcciones.setBounds(670, 520, 120, 16);

        btnMover.setText("Mover personaje");
        btnMover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoverActionPerformed(evt);
            }
        });
        pnlTableroDeJuego.add(btnMover);
        btnMover.setBounds(540, 540, 170, 23);

        btnAtacar.setText("Atacar a un enemigo");
        btnAtacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtacarActionPerformed(evt);
            }
        });
        pnlTableroDeJuego.add(btnAtacar);
        btnAtacar.setBounds(730, 540, 170, 23);

        btnIniciarPartida.setText("Iniciar Partida");
        btnIniciarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarPartidaActionPerformed(evt);
            }
        });
        pnlTableroDeJuego.add(btnIniciarPartida);
        btnIniciarPartida.setBounds(620, 490, 190, 23);

        btnUsarArticulo.setText("Usar un articulo");
        btnUsarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsarArticuloActionPerformed(evt);
            }
        });
        pnlTableroDeJuego.add(btnUsarArticulo);
        btnUsarArticulo.setBounds(630, 570, 170, 23);

        btnTerminarTurno.setText("Terminar turno");
        btnTerminarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarTurnoActionPerformed(evt);
            }
        });
        pnlTableroDeJuego.add(btnTerminarTurno);
        btnTerminarTurno.setBounds(530, 600, 200, 23);

        btnNuevoTurno.setText("Nuevo turno");
        btnNuevoTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoTurnoActionPerformed(evt);
            }
        });
        pnlTableroDeJuego.add(btnNuevoTurno);
        btnNuevoTurno.setBounds(740, 600, 160, 23);

        fieldIDTablero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIDTableroActionPerformed(evt);
            }
        });
        pnlTableroDeJuego.add(fieldIDTablero);
        fieldIDTablero.setBounds(90, 550, 64, 22);

        lblIDTablero.setForeground(new java.awt.Color(0, 0, 0));
        lblIDTablero.setText("Ingresa el ID del tablero que quieras jugar");
        pnlTableroDeJuego.add(lblIDTablero);
        lblIDTablero.setBounds(20, 520, 250, 16);

        fieldArticuloAUsar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldArticuloAUsarActionPerformed(evt);
            }
        });
        pnlTableroDeJuego.add(fieldArticuloAUsar);
        fieldArticuloAUsar.setBounds(950, 430, 70, 22);

        lblSeleccionarArticulo.setForeground(new java.awt.Color(0, 0, 0));
        lblSeleccionarArticulo.setText("Selecciona un articulo a utilizar");
        pnlTableroDeJuego.add(lblSeleccionarArticulo);
        lblSeleccionarArticulo.setBounds(900, 410, 190, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlTableroDeJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 1253, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTableroDeJuego, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtaqueAbajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtaqueAbajoActionPerformed
        tableroNuevo.ataqueJugadorY(false);

        usuario.desactivarBotonesAtaque(lblDireccionAtaque, btnAtaqueArriba, btnAtaqueAbajo, btnAtaqueDerecha, btnAtaqueIzquierda);
        btnTerminarTurno.setVisible(true);
        btnTerminarTurno.setEnabled(true);
    }//GEN-LAST:event_btnAtaqueAbajoActionPerformed

    private void btnAtaqueIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtaqueIzquierdaActionPerformed
        tableroNuevo.ataqueJugadorX(false);

        usuario.desactivarBotonesAtaque(lblDireccionAtaque, btnAtaqueArriba, btnAtaqueAbajo, btnAtaqueDerecha, btnAtaqueIzquierda);
        btnTerminarTurno.setVisible(true);
        btnTerminarTurno.setEnabled(true);
    }//GEN-LAST:event_btnAtaqueIzquierdaActionPerformed

    private void btnAtaqueDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtaqueDerechaActionPerformed
        tableroNuevo.ataqueJugadorX(true);

        usuario.desactivarBotonesAtaque(lblDireccionAtaque, btnAtaqueArriba, btnAtaqueAbajo, btnAtaqueDerecha, btnAtaqueIzquierda);
        btnTerminarTurno.setVisible(true);
        btnTerminarTurno.setEnabled(true);
    }//GEN-LAST:event_btnAtaqueDerechaActionPerformed

    private void btnAtaqueArribaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtaqueArribaActionPerformed
        tableroNuevo.ataqueJugadorY(true);

        usuario.desactivarBotonesAtaque(lblDireccionAtaque, btnAtaqueArriba, btnAtaqueAbajo, btnAtaqueDerecha, btnAtaqueIzquierda);
        btnTerminarTurno.setVisible(true);
        btnTerminarTurno.setEnabled(true);
    }//GEN-LAST:event_btnAtaqueArribaActionPerformed

    private void btnRegresarPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarPrincipalActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarPrincipalActionPerformed

    private void btnMostrarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarInventarioActionPerformed
        Inventario inventario = new Inventario(usuario);
        inventario.setVisible(true);
    }//GEN-LAST:event_btnMostrarInventarioActionPerformed

    private void fieldPersonajePrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPersonajePrincipalActionPerformed
        String principal = fieldPersonajePrincipal.getText();
        int personajePrincipal = Integer.parseInt(principal) - 1;
        usuario.almacenarPrincipalUsuario(personajePrincipal);
        boxDificultad.setVisible(true);
        lblDificultad.setVisible(true);
        fieldPersonajePrincipal.setEnabled(false);
        lblJugadorPrincipal.setEnabled(false);
    }//GEN-LAST:event_fieldPersonajePrincipalActionPerformed

    private void boxDificultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxDificultadActionPerformed
        String dificultadString = boxDificultad.getSelectedItem().toString();
        int dificultad = Integer.parseInt(dificultadString);
        ia.setDificultad(dificultad);

        fieldIDTablero.setVisible(true);
        lblIDTablero.setVisible(true);
        btnMostrarTableros.setVisible(true);
        boxDificultad.setEnabled(false);
    }//GEN-LAST:event_boxDificultadActionPerformed

    private void btnMostrarTablerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTablerosActionPerformed
        String textoLeido;
        textoLeido = archivo.abrirArchivo();
        System.out.println(textoLeido);
        JOptionPane.showMessageDialog(rootPane, textoLeido, "TABLEROS", 1);
    }//GEN-LAST:event_btnMostrarTablerosActionPerformed

    private void btnCargarMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarMapaActionPerformed

        fieldIDTablero.setVisible(true);
        lblIDTablero.setVisible(true);
        String id = fieldIDTablero.getText();
        System.out.println("id(tableroFrame) = " + id);

        crearTablero.leerArchivo(id);
        tableroNuevo = crearTablero.getNuevoTablero();
        tableroNuevo.anadirBotones(pnlTablero, this);

        btnCargarMapa.setVisible(false);
        btnMostrarTableros.setVisible(false);
        boxDificultad.setVisible(false);
        lblDificultad.setVisible(false);
        lblJugadorPrincipal.setVisible(true);
        fieldPersonajePrincipal.setVisible(true);
        btnIniciarPartida.setVisible(true);
        fieldIDTablero.setVisible(false);
        lblIDTablero.setVisible(false);

    }//GEN-LAST:event_btnCargarMapaActionPerformed

    private void btnMoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoverActionPerformed
        usuario.activarBotonesMovimiento(lblDireccionMovimiento, btnMovimientoArriba, btnMovimientoAbajo, btnMovimientoDerecha, btnMovimientoIzquierda);

        btnAtacar.setEnabled(false);
        btnMover.setEnabled(false);
    }//GEN-LAST:event_btnMoverActionPerformed

    private void btnAtacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtacarActionPerformed
        usuario.activarBotonesAtaque(lblDireccionAtaque, btnAtaqueArriba, btnAtaqueAbajo, btnAtaqueDerecha, btnAtaqueIzquierda);

        btnMover.setEnabled(false);
        btnAtacar.setEnabled(false);
    }//GEN-LAST:event_btnAtacarActionPerformed

    private void btnIniciarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarPartidaActionPerformed
        btnMover.setVisible(true);
        btnAtacar.setVisible(true);
        btnUsarArticulo.setVisible(true);
        btnIniciarPartida.setVisible(false);
        lblAcciones.setVisible(true);
    }//GEN-LAST:event_btnIniciarPartidaActionPerformed

    private void btnMovimientoArribaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovimientoArribaActionPerformed
        tableroNuevo.moverJugadorY(true);
        tableroNuevo.pintarMapa();
        tableroNuevo.actualizarTablero(pnlTablero);
        tableroNuevo.anadirBotones(pnlTablero, this);

        usuario.desactivarBotonesMovimiento(lblDireccionMovimiento, btnMovimientoArriba, btnMovimientoAbajo, btnMovimientoDerecha, btnMovimientoIzquierda);
        btnTerminarTurno.setVisible(true);
        btnTerminarTurno.setEnabled(true);
    }//GEN-LAST:event_btnMovimientoArribaActionPerformed

    private void btnMovimientoAbajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovimientoAbajoActionPerformed
        tableroNuevo.moverJugadorY(false);
        tableroNuevo.pintarMapa();
        tableroNuevo.actualizarTablero(pnlTablero);
        tableroNuevo.anadirBotones(pnlTablero, this);

        usuario.desactivarBotonesMovimiento(lblDireccionMovimiento, btnMovimientoArriba, btnMovimientoAbajo, btnMovimientoDerecha, btnMovimientoIzquierda);
        btnTerminarTurno.setVisible(true);
        btnTerminarTurno.setEnabled(true);
    }//GEN-LAST:event_btnMovimientoAbajoActionPerformed

    private void btnMovimientoDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovimientoDerechaActionPerformed
        tableroNuevo.moverJugadorX(true);
        tableroNuevo.pintarMapa();
        tableroNuevo.actualizarTablero(pnlTablero);
        tableroNuevo.anadirBotones(pnlTablero, this);

        usuario.desactivarBotonesMovimiento(lblDireccionMovimiento, btnMovimientoArriba, btnMovimientoAbajo, btnMovimientoDerecha, btnMovimientoIzquierda);
        btnTerminarTurno.setVisible(true);
        btnTerminarTurno.setEnabled(true);
    }//GEN-LAST:event_btnMovimientoDerechaActionPerformed

    private void btnMovimientoIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovimientoIzquierdaActionPerformed
        tableroNuevo.moverJugadorX(false);
        tableroNuevo.pintarMapa();
        tableroNuevo.actualizarTablero(pnlTablero);
        tableroNuevo.anadirBotones(pnlTablero, this);

        usuario.desactivarBotonesMovimiento(lblDireccionMovimiento, btnMovimientoArriba, btnMovimientoAbajo, btnMovimientoDerecha, btnMovimientoIzquierda);
        btnTerminarTurno.setVisible(true);
        btnTerminarTurno.setEnabled(true);
    }//GEN-LAST:event_btnMovimientoIzquierdaActionPerformed

    private void btnTerminarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarTurnoActionPerformed
        tableroNuevo.actualizarTablero(pnlTablero);
        tableroNuevo.anadirBotones(pnlTablero, this);
        btnTerminarTurno.setEnabled(false);
        btnNuevoTurno.setVisible(true);
        btnNuevoTurno.setEnabled(true);
        btnAtacar.setEnabled(false);
        btnMover.setEnabled(false);
        btnUsarArticulo.setEnabled(false);
        usuario.desactivarBotonesMovimiento(lblDireccionMovimiento, btnMovimientoArriba, btnMovimientoAbajo, btnMovimientoDerecha, btnMovimientoIzquierda);

        lblAcciones.setVisible(false);
        btnAtacar.setVisible(false);
        btnMover.setVisible(false);
        btnUsarArticulo.setVisible(false);
        btnIniciarPartida.setVisible(false);

        tableroNuevo.realizarTurnoIA();
        tableroNuevo.actualizarTablero(pnlTablero);
        tableroNuevo.anadirBotones(pnlTablero, this);

    }//GEN-LAST:event_btnTerminarTurnoActionPerformed

    private void btnUsarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsarArticuloActionPerformed
        fieldArticuloAUsar.setVisible(true);
        lblSeleccionarArticulo.setVisible(true);

    }//GEN-LAST:event_btnUsarArticuloActionPerformed

    private void btnNuevoTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoTurnoActionPerformed
        System.out.println("cambiando el turno");
        btnAtacar.setVisible(true);
        btnMover.setVisible(true);
        btnUsarArticulo.setVisible(true);
        btnAtacar.setEnabled(true);
        btnMover.setEnabled(true);
        btnUsarArticulo.setEnabled(true);
        tableroNuevo.actualizarTablero(pnlTablero);
        tableroNuevo.anadirBotones(pnlTablero, this);
        btnNuevoTurno.setEnabled(false);

    }//GEN-LAST:event_btnNuevoTurnoActionPerformed

    private void fieldIDTableroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIDTableroActionPerformed
        btnCargarMapa.setVisible(true);
    }//GEN-LAST:event_fieldIDTableroActionPerformed

    private void fieldArticuloAUsarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldArticuloAUsarActionPerformed
        String articuloAUtilizar = fieldArticuloAUsar.getText();
        int articulo = Integer.parseInt(articuloAUtilizar) - 1;

        tableroNuevo.usarArticulo(articulo);
        fieldArticuloAUsar.setVisible(false);
        lblSeleccionarArticulo.setVisible(false);
    }//GEN-LAST:event_fieldArticuloAUsarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxDificultad;
    private javax.swing.JButton btnAtacar;
    private javax.swing.JButton btnAtaqueAbajo;
    private javax.swing.JButton btnAtaqueArriba;
    private javax.swing.JButton btnAtaqueDerecha;
    private javax.swing.JButton btnAtaqueIzquierda;
    private javax.swing.JButton btnCargarMapa;
    private javax.swing.JButton btnIniciarPartida;
    private javax.swing.JButton btnMostrarInventario;
    private javax.swing.JButton btnMostrarTableros;
    private javax.swing.JButton btnMover;
    private javax.swing.JButton btnMovimientoAbajo;
    private javax.swing.JButton btnMovimientoArriba;
    private javax.swing.JButton btnMovimientoDerecha;
    private javax.swing.JButton btnMovimientoIzquierda;
    private javax.swing.JButton btnNuevoTurno;
    private javax.swing.JButton btnRegresarPrincipal;
    private javax.swing.JButton btnTerminarTurno;
    private javax.swing.JButton btnUsarArticulo;
    private javax.swing.JTextField fieldArticuloAUsar;
    private javax.swing.JTextField fieldIDTablero;
    private javax.swing.JTextField fieldPersonajePrincipal;
    private javax.swing.JLabel lblAcciones;
    private javax.swing.JLabel lblDificultad;
    private javax.swing.JLabel lblDireccionAtaque;
    private javax.swing.JLabel lblDireccionMovimiento;
    private javax.swing.JLabel lblIDTablero;
    private javax.swing.JLabel lblJugadorPrincipal;
    private javax.swing.JLabel lblSeleccionarArticulo;
    private javax.swing.JLabel lblTableroDeJuego;
    private javax.swing.JPanel pnlTablero;
    private javax.swing.JPanel pnlTableroDeJuego;
    // End of variables declaration//GEN-END:variables
}
