package com.mycompany.juegopeleasgui.fe;

import com.mycompany.juegopeleasgui.be.articulos.Articulo;
import com.mycompany.juegopeleasgui.be.jugadores.IA;
import com.mycompany.juegopeleasgui.be.jugadores.Usuario;
import com.mycompany.juegopeleasgui.be.personajes.Jugable;

public class Tienda extends javax.swing.JFrame {

    /**
     * Creates new form Tienda
     */
    private Usuario usuario;
    private Jugable[] listaJugables;
    private Articulo[] listaArticulos;
    private IA ia;

    public Tienda(Usuario usuario, IA ia) {
        this.usuario = usuario;
        this.ia = ia;
        initComponents();
        lblCantidadOro.setText(usuario.getOro() + "");
        listaJugables = usuario.getListaJugables();
        listaArticulos = usuario.getListaArticulos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTienda = new javax.swing.JPanel();
        lblTienda = new javax.swing.JLabel();
        lblOro = new javax.swing.JLabel();
        lblCantidadOro = new javax.swing.JLabel();
        lblPersonajes = new javax.swing.JLabel();
        lblArticulos = new javax.swing.JLabel();
        btnCaballero = new javax.swing.JButton();
        btnArquero = new javax.swing.JButton();
        btnDragon = new javax.swing.JButton();
        btnGigante = new javax.swing.JButton();
        btnMago = new javax.swing.JButton();
        btnCapaMovilidad = new javax.swing.JButton();
        btnDano = new javax.swing.JButton();
        btnElixirVerde = new javax.swing.JButton();
        btnMovilidad = new javax.swing.JButton();
        btnSemillaVida = new javax.swing.JButton();
        btnVida = new javax.swing.JButton();
        separador = new javax.swing.JSeparator();
        btnRegresarMenuPrincipal = new javax.swing.JButton();
        btnSeleccionMapa = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlTienda.setBackground(new java.awt.Color(255, 170, 80));
        pnlTienda.setLayout(null);

        lblTienda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTienda.setForeground(new java.awt.Color(0, 0, 0));
        lblTienda.setText("Tienda");
        pnlTienda.add(lblTienda);
        lblTienda.setBounds(145, 6, 63, 29);

        lblOro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblOro.setForeground(new java.awt.Color(0, 0, 0));
        lblOro.setText("Oro del Jugador:");
        pnlTienda.add(lblOro);
        lblOro.setBounds(93, 47, 91, 16);

        lblCantidadOro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCantidadOro.setForeground(new java.awt.Color(0, 0, 0));
        lblCantidadOro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlTienda.add(lblCantidadOro);
        lblCantidadOro.setBounds(202, 47, 34, 16);

        lblPersonajes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPersonajes.setForeground(new java.awt.Color(0, 0, 0));
        lblPersonajes.setText("Personajes");
        pnlTienda.add(lblPersonajes);
        lblPersonajes.setBounds(46, 81, 66, 16);

        lblArticulos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblArticulos.setForeground(new java.awt.Color(0, 0, 0));
        lblArticulos.setText("Articulos");
        pnlTienda.add(lblArticulos);
        lblArticulos.setBounds(260, 81, 49, 16);

        btnCaballero.setText("Caballero  Coste = 200 ");
        btnCaballero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaballeroActionPerformed(evt);
            }
        });
        pnlTienda.add(btnCaballero);
        btnCaballero.setBounds(6, 103, 170, 23);

        btnArquero.setText("Arquero    Coste = 200 ");
        btnArquero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArqueroActionPerformed(evt);
            }
        });
        pnlTienda.add(btnArquero);
        btnArquero.setBounds(6, 138, 170, 23);

        btnDragon.setText("Dragon   Coste = 200 ");
        btnDragon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDragonActionPerformed(evt);
            }
        });
        pnlTienda.add(btnDragon);
        btnDragon.setBounds(6, 179, 170, 23);

        btnGigante.setText("Gigante   Coste = 200 ");
        btnGigante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiganteActionPerformed(evt);
            }
        });
        pnlTienda.add(btnGigante);
        btnGigante.setBounds(6, 220, 170, 23);

        btnMago.setText("Mago   Coste = 200 ");
        btnMago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMagoActionPerformed(evt);
            }
        });
        pnlTienda.add(btnMago);
        btnMago.setBounds(6, 261, 170, 23);

        btnCapaMovilidad.setText("Capa de Movilidad    Coste = 75");
        btnCapaMovilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapaMovilidadActionPerformed(evt);
            }
        });
        pnlTienda.add(btnCapaMovilidad);
        btnCapaMovilidad.setBounds(202, 103, 210, 23);

        btnDano.setText("Dano    Coste = 125");
        btnDano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanoActionPerformed(evt);
            }
        });
        pnlTienda.add(btnDano);
        btnDano.setBounds(202, 138, 210, 23);

        btnElixirVerde.setText("Elixir Verde   Coste = 25");
        btnElixirVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElixirVerdeActionPerformed(evt);
            }
        });
        pnlTienda.add(btnElixirVerde);
        btnElixirVerde.setBounds(202, 179, 210, 23);

        btnMovilidad.setText("Movilidad    Coste = 500");
        btnMovilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovilidadActionPerformed(evt);
            }
        });
        pnlTienda.add(btnMovilidad);
        btnMovilidad.setBounds(202, 220, 210, 23);

        btnSemillaVida.setText("Semilla de la Vida = 150");
        btnSemillaVida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSemillaVidaActionPerformed(evt);
            }
        });
        pnlTienda.add(btnSemillaVida);
        btnSemillaVida.setBounds(202, 261, 210, 23);

        btnVida.setText("Vida = 80");
        btnVida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVidaActionPerformed(evt);
            }
        });
        pnlTienda.add(btnVida);
        btnVida.setBounds(202, 302, 210, 23);
        pnlTienda.add(separador);
        separador.setBounds(0, 337, 426, 10);

        btnRegresarMenuPrincipal.setText("Regresar al Menu Principal");
        btnRegresarMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarMenuPrincipalActionPerformed(evt);
            }
        });
        pnlTienda.add(btnRegresarMenuPrincipal);
        btnRegresarMenuPrincipal.setBounds(80, 390, 230, 23);

        btnSeleccionMapa.setText("SeleccionMapa");
        btnSeleccionMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionMapaActionPerformed(evt);
            }
        });
        pnlTienda.add(btnSeleccionMapa);
        btnSeleccionMapa.setBounds(180, 350, 183, 23);

        btnInventario.setText("Mostrar Inventario");
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        pnlTienda.add(btnInventario);
        btnInventario.setBounds(10, 350, 140, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTienda, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTienda, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarMenuPrincipalActionPerformed
        this.setVisible(false);

    }//GEN-LAST:event_btnRegresarMenuPrincipalActionPerformed

    private void btnCaballeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaballeroActionPerformed
        usuario.comprarJugables(listaJugables[0], usuario.getOro());
        lblCantidadOro.setText(usuario.getOro() + "");

    }//GEN-LAST:event_btnCaballeroActionPerformed

    private void btnArqueroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArqueroActionPerformed
        usuario.comprarJugables(listaJugables[1], usuario.getOro());
        lblCantidadOro.setText(usuario.getOro() + "");

    }//GEN-LAST:event_btnArqueroActionPerformed

    private void btnDragonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDragonActionPerformed
        usuario.comprarJugables(listaJugables[2], usuario.getOro());
        lblCantidadOro.setText(usuario.getOro() + "");
    }//GEN-LAST:event_btnDragonActionPerformed

    private void btnGiganteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiganteActionPerformed
        usuario.comprarJugables(listaJugables[3], usuario.getOro());
        lblCantidadOro.setText(usuario.getOro() + "");
    }//GEN-LAST:event_btnGiganteActionPerformed

    private void btnMagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMagoActionPerformed
        usuario.comprarJugables(listaJugables[4], usuario.getOro());
        lblCantidadOro.setText(usuario.getOro() + "");
    }//GEN-LAST:event_btnMagoActionPerformed

    private void btnCapaMovilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapaMovilidadActionPerformed
        usuario.comprarArticulos(listaArticulos[0], usuario.getOro());
        lblCantidadOro.setText(usuario.getOro() + "");
    }//GEN-LAST:event_btnCapaMovilidadActionPerformed

    private void btnDanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanoActionPerformed
        usuario.comprarArticulos(listaArticulos[1], usuario.getOro());
        lblCantidadOro.setText(usuario.getOro() + "");
    }//GEN-LAST:event_btnDanoActionPerformed

    private void btnElixirVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElixirVerdeActionPerformed
        usuario.comprarArticulos(listaArticulos[2], usuario.getOro());
        lblCantidadOro.setText(usuario.getOro() + "");
    }//GEN-LAST:event_btnElixirVerdeActionPerformed

    private void btnMovilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovilidadActionPerformed
        usuario.comprarArticulos(listaArticulos[3], usuario.getOro());
        lblCantidadOro.setText(usuario.getOro() + "");
    }//GEN-LAST:event_btnMovilidadActionPerformed

    private void btnSemillaVidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSemillaVidaActionPerformed
        usuario.comprarArticulos(listaArticulos[4], usuario.getOro());
        lblCantidadOro.setText(usuario.getOro() + "");
    }//GEN-LAST:event_btnSemillaVidaActionPerformed

    private void btnVidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVidaActionPerformed
        usuario.comprarArticulos(listaArticulos[5], usuario.getOro());
        lblCantidadOro.setText(usuario.getOro() + "");
    }//GEN-LAST:event_btnVidaActionPerformed

    private void btnSeleccionMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionMapaActionPerformed
        TableroDeJuego abrir = new TableroDeJuego(usuario, ia);
        //  abrir.setExtendedState(TableroDeJuego.MAXIMIZED_BOTH);
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSeleccionMapaActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        Inventario inventario = new Inventario(usuario);
        inventario.setVisible(true);
    }//GEN-LAST:event_btnInventarioActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArquero;
    private javax.swing.JButton btnCaballero;
    private javax.swing.JButton btnCapaMovilidad;
    private javax.swing.JButton btnDano;
    private javax.swing.JButton btnDragon;
    private javax.swing.JButton btnElixirVerde;
    private javax.swing.JButton btnGigante;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnMago;
    private javax.swing.JButton btnMovilidad;
    private javax.swing.JButton btnRegresarMenuPrincipal;
    private javax.swing.JButton btnSeleccionMapa;
    private javax.swing.JButton btnSemillaVida;
    private javax.swing.JButton btnVida;
    private javax.swing.JLabel lblArticulos;
    private javax.swing.JLabel lblCantidadOro;
    private javax.swing.JLabel lblOro;
    private javax.swing.JLabel lblPersonajes;
    private javax.swing.JLabel lblTienda;
    private javax.swing.JPanel pnlTienda;
    private javax.swing.JSeparator separador;
    // End of variables declaration//GEN-END:variables
}
